CREATE TABLE  lifetech.heaterhistoric (
id SERIAL PRIMARY KEY,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
startdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
endingdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
state VARCHAR(255),
heaterid VARCHAR(255)
);

CREATE TABLE  lifetech.lighthistoric (
id SERIAL PRIMARY KEY,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
startdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
endingdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
state VARCHAR(255),
lightid VARCHAR(255),
color VARCHAR(255),
percentage VARCHAR(255)
);

CREATE TABLE  lifetech.clockhistoric (
id SERIAL PRIMARY KEY,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
startdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
endingdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
state VARCHAR(255),
clockid VARCHAR(255)
);

CREATE TABLE  lifetech.shutterhistoric (
id SERIAL PRIMARY KEY,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
startdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
endingdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
state VARCHAR(255),
shutterid VARCHAR(255),
percentage VARCHAR(255)
);

CREATE TABLE  lifetech.straphistoric (
id SERIAL PRIMARY KEY,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
startdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
endingdate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
state VARCHAR(255),
strapid VARCHAR(255)
);