CREATE TABLE objectiot (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
optlock TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
name VARCHAR(255),
status VARCHAR (255),
date TIMESTAMP(3),
minValue INT ,
maximValue INT ,
actualValue INT
);